### ISSUE TITLE
希望添加一个七牛的参数

### ISSUE THREAD

**Issue by longsays** [7sDream/rikka#4]
增加一个七牛参数,使上传的图片不是放在根目录,而是可以自定义目录,谢谢

**Comment by longsays** [comment]
"bpath"可以使用吗?

**Comment by 7sDream** [comment]
@longsays 

本来开始写这个插件的时候就计划支持分文件夹的，可是因为用的七牛云的 GO SDK 貌似有 bug，这个功能暂时用不了，我已经给七牛 SDK 提了 Issue 了，但是暂时没人回。

https://github.com/qiniu/api.v7/issues/47

所以我把 `bpath` 参数暂时禁用了，见代码：https://github.com/7sDream/rikka/blob/master/plugins/qiniu/init.go#L76

等什么时候七牛官方回复这个 Bug 应该怎么办，修好之后这个参数就可以用了。

**Comment by longsays** [comment]
谢谢

**Comment by 7sDream** [comment]
@longsays 

0.2.2 版本已发布，`bpath` 参数已经可用了，参见：https://github.com/7sDream/rikka/blob/master/plugins/qiniu/README.zh.md#参数
