### ISSUE TITLE
复制图片 URL 时所有标签都只能复制 BBCode 格式的 URL

### ISSUE THREAD

**Issue by tangx** [7sDream/rikka#6]
版本，七牛DEMO Version 0.2.3

无论点击任何标签复制URL的时候，结果总是 “ BBCode ”，也只有BBCode的标签变为 【copied】

**Comment by 7sDream** [comment]
可能是由于上次我们把 JS 脚本用 ES5 重写了一遍造成的问题。

马上去看看……

**Comment by 7sDream** [comment]
@uyinn 

已搞定。

http://7sdream-rikka-qiniu.daoapp.io/view/4afd6dee-80ef-48fb-a276-2d10c78cdc3d.png

可以到上面这个 URL 测试。

由于浏览器缓存原因，打开上面那个 URL 之后可能要用 `Ctrl+F5` 强制刷新之后才能没有 Bug。

**Comment by tangx** [comment]
daocloud.io上面的镜像 023和024的TAG顺序反了，直接抓最新版的话，是023

**Comment by 7sDream** [comment]
daocloud.io 你能抓我镜像么……话说那不是私有的么……

我去瞅瞅，难道是我交了个月费自动变成公有的了？

**Comment by 7sDream** [comment]
@uyinn 

应该不会呀，我还瞅了一眼 Dockerhub，latest tag 也没错呀……QwQ

**Comment by tangx** [comment]
![image](https://cloud.githubusercontent.com/assets/7335398/18512449/c9e8cd66-7abb-11e6-8115-4fa6218c9e4c.png)

测试过了，024抓了10多分钟没抓下来。023的话4分钟就搞定了。 这个023就是这个issue的。

要不再推一个025？

**Comment by 7sDream** [comment]
恩这是 dockerhub 的镜像，我刚又传了一遍，我去试试看能不能行。

或者你试试用最下面的 latest 的，那个永远是最新的。

**Comment by tangx** [comment]
OK, 使用latest就好了。 THX

**Comment by 7sDream** [comment]
@uyinn 

恩，其实我感觉刚刚有可能是 DaoCloud 他们那边和 Dockerhub 的网络出了点问题……应该不是 0.2.4 tag 的问题……

不过不管咋样，好了就好~
