### ISSUE TITLE
DaoCloud现在已经不能免费部署了

### ISSUE THREAD

**Issue by LittleModesty** [7sDream/rikka#7]

**Comment by 7sDream** [comment]
什么意思？那为啥我的 Demo 还在跑…………

**Comment by LittleModesty** [comment]
![](http://csy123-img.daoapp.io/files/4369a780-a777-428c-ae53-9d1a6659b424.png)

[URL](http://docs.daocloud.io/app-deploy-mgmt/cloud-limited-resources)

应用好像要被回收了

**Comment by 7sDream** [comment]
嗷，我看到了……还好吧，两个星期去重启一次呗……
恩，我也只是把 Demo 部署到 DaoCloud 并且用它举例子写 wiki 来着……我自己用的 Rikka 是部署在腾讯云学生机上的 =。=

恩，其实用起来也没太大问题，时常去重启下就好……

**Comment by 7sDream** [comment]
Daocloud 已经完全没有测试环境可以用了，目前 Demo 换到了 VPS 上，遂关闭。
