### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by figwh** [7sDream/rikka#8]
api/upload 接口处理跨域了吗？在 js 脚本中调用这个接口报了跨域问题，谢谢。

**Comment by 7sDream** [comment]
@ratoy 

暂时没有

目前的 API 接口是给命令行 CLI 用的（因为本身就是带前端界面的项目）之前没有考虑给其他网站直接在前端脚本调用……

这几天都比较忙估计是没时间写了，如果 8 月有时间的话我考虑加一下。

你也可以自己加然后提 PR~

**Comment by 7sDream** [comment]
时隔一万年来更新了下这个项目。

0.8.0 增加了 API 的跨域支持，启动的时候添加 `-corsAllowOrigin '*'` 参数就 OK 了。
